In [1]:
# This line imports the pandas library so the AISC section data can be loaded and filtered.
import pandas as pd
# This line imports matplotlib so we can plot our results at the end.
import matplotlib.pyplot as plt
# This line imports seaborn to make the plot look clean and professional.
import seaborn as sns
# This line loads the AISC section property CSV file into Python.
aisc_data = pd.read_csv('CSV.csv')
# This line displays info about the dataset to confirm it loaded correctly.
aisc_data.head()
aisc_data.info()
aisc_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2299 entries, 0 to 2298
Columns: 166 entries, Type to WGo.1
dtypes: float64(19), int64(1), object(146)
memory usage: 2.9+ MB

,W,A,Ix,Zx,Sx,rx,Iy,Zy,Sy,ry,W.1,A.1,Ix.1,Zx.1,Sx.1,rx.1,Iy.1,Zy.1,Sy.1,ry.1
count,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000
mean,67.141831,19.406348,1428.833506,124.493464,100.423190,3.740022,315.774820,57.080749,40.696728,2.491572,99.929326,12520.141366,594.689431,2040.161448,1645.708100,94.997621,131.434278,935.429112,666.946991,63.283893
std,92.600992,27.099036,5193.723011,320.945526,271.426099,3.387731,695.342232,99.986852,71.939291,1.668471,137.953587,17484.855557,2161.508817,5259.581787,4448.127957,86.048271,289.434215,1638.620139,1179.130257,42.370238
min,0.850000,0.234000,0.016000,0.055500,0.038800,0.253000,0.016000,0.055500,0.038800,0.253000,1.260000,151.000000,0.006660,0.909000,0.636000,6.430000,0.006670,0.909000,0.636000,6.430000
25%,14.400000,4.140000,7.530000,4.520000,2.820000,1.240000,7.055000,4.280000,2.650000,1.260000,21.400000,2670.000000,3.130000,74.100000,46.200000,31.500000,2.935000,70.100000,43.400000,32.000000
50%,32.630000,9.500000,56.200000,18.400000,12.300000,2.500000,38.400000,14.900000,9.800000,2.040000,48.500000,6130.000000,23.400000,302.000000,202.000000,63.500000,16.000000,244.000000,161.000000,51.800000
75%,82.425000,23.100000,580.000000,96.150000,67.200000,5.235000,277.000000,65.250000,44.850000,3.390000,122.500000,14900.000000,241.500000,1575.000000,1100.000000,133.000000,115.000000,1070.000000,735.000000,86.100000
max,925.000000,272.000000,73000.000000,4130.000000,3390.000000,18.000000,7250.000000,1020.000000,656.000000,9.780000,1380.000000,175000.000000,30400.000000,67700.000000,55600.000000,457.000000,3020.000000,16700.000000,10800.000000,248.000000

In [2]:
# This line imports the pandas library so the AISC section data can be loaded and filtered.
import pandas as pd
# This line imports matplotlib so we can plot our results at the end.
import matplotlib.pyplot as plt
# This line imports seaborn to make the plot look clean and professional.
import seaborn as sns
# This line loads the AISC section property CSV file into Python.
aisc_data = pd.read_csv('CSV.csv')
# This line displays info about the dataset to confirm it loaded correctly.
aisc_data.head()
aisc_data.info()
aisc_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2299 entries, 0 to 2298
Columns: 166 entries, Type to WGo.1
dtypes: float64(19), int64(1), object(146)
memory usage: 2.9+ MB

,W,A,Ix,Zx,Sx,rx,Iy,Zy,Sy,ry,W.1,A.1,Ix.1,Zx.1,Sx.1,rx.1,Iy.1,Zy.1,Sy.1,ry.1
count,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000,2299.000000
mean,67.141831,19.406348,1428.833506,124.493464,100.423190,3.740022,315.774820,57.080749,40.696728,2.491572,99.929326,12520.141366,594.689431,2040.161448,1645.708100,94.997621,131.434278,935.429112,666.946991,63.283893
std,92.600992,27.099036,5193.723011,320.945526,271.426099,3.387731,695.342232,99.986852,71.939291,1.668471,137.953587,17484.855557,2161.508817,5259.581787,4448.127957,86.048271,289.434215,1638.620139,1179.130257,42.370238
min,0.850000,0.234000,0.016000,0.055500,0.038800,0.253000,0.016000,0.055500,0.038800,0.253000,1.260000,151.000000,0.006660,0.909000,0.636000,6.430000,0.006670,0.909000,0.636000,6.430000
25%,14.400000,4.140000,7.530000,4.520000,2.820000,1.240000,7.055000,4.280000,2.650000,1.260000,21.400000,2670.000000,3.130000,74.100000,46.200000,31.500000,2.935000,70.100000,43.400000,32.000000
50%,32.630000,9.500000,56.200000,18.400000,12.300000,2.500000,38.400000,14.900000,9.800000,2.040000,48.500000,6130.000000,23.400000,302.000000,202.000000,63.500000,16.000000,244.000000,161.000000,51.800000
75%,82.425000,23.100000,580.000000,96.150000,67.200000,5.235000,277.000000,65.250000,44.850000,3.390000,122.500000,14900.000000,241.500000,1575.000000,1100.000000,133.000000,115.000000,1070.000000,735.000000,86.100000
max,925.000000,272.000000,73000.000000,4130.000000,3390.000000,18.000000,7250.000000,1020.000000,656.000000,9.780000,1380.000000,175000.000000,30400.000000,67700.000000,55600.000000,457.000000,3020.000000,16700.000000,10800.000000,248.000000

In [3]:
# This line filters the dataset to only keep rows where the Type column equals 'W'.
w_shapes = aisc_data[aisc_data['Type'] == 'W'].copy()
# This line resets the index of the filtered dataframe so the row numbers start from zero.
w_shapes = w_shapes.reset_index(drop=True)
# This line prints how many W-shapes are in the database so we can confirm the filter worked.
print(f'Total W-shapes available: {len(w_shapes)}')

Total W-shapes available: 289

In [4]:
# This line defines a function that calculates the shear lag factor U per AISC Table D3.1 Case 2.
def calculate_U(x_bar, L):
    # This line applies the shear lag formula where x_bar is the centroid distance and L is the connection length.
    U = 1 - (x_bar / L)
    return U

In [ ]:
# This line defines a function that calculates tensile rupture strength given a shape name and connection length.
def tensile_rupture(shape_name, L):
    # This line looks up the row in the W-shapes dataframe that matches the shape name entered.
    row = w_shapes[w_shapes['AISC_Manual_Label'] == shape_name]
    # This line extracts the gross area Ag from the matched row and converts it to a float for math.
    Ag = float(row['A'].values[0])
    # This line extracts the flange width bf from the matched row and converts it to a float for math.
    bf = float(row['bf'].values[0])
    # This line calculates x_bar as bf divided by 4, which is the centroid distance for a W-shape connected at the flanges.
    x_bar = bf / 4
    # This line sets Fu to 65 ksi, the ultimate tensile stress for all standard ASTM A992 W-shapes.
    Fu = 65
    # This line sets the net area An equal to Ag because a welded connection has no bolt holes to deduct.
    An = Ag
    # This line calls the calculate_U function to find the shear lag factor.
    U = calculate_U(x_bar, L)
    # This line calculates the effective net area Ae.
    Ae = An * U
    # This line calculates the nominal tensile rupture strength Pn.
    Pn = Fu * Ae
    # This line calculates the LRFD available strength using a resistance factor of 0.75.
    LRFD = 0.75 * Pn
    # This line calculates the ASD available strength using a safety factor of 2.00.
    ASD = Pn / 2.00
    # These lines print a formatted summary of all inputs and outputs for the shape.
    print(f'---------------------------------------')
    print(f' Results for {shape_name}')
    print(f'---------------------------------------')
    print(f' Connection Length (L)    = {L} in')
    print(f' Gross Area (Ag)          = {Ag} in^2')
    print(f' Flange Width (bf)        = {bf} in')
    print(f' Centroid Distance (xbar) = {x_bar:.3f} in')
    print(f' Shear Lag Factor (U)     = {U:.4f}')
    print(f' Effective Net Area (Ae)  = {Ae:.3f} in^2')
    print(f' Nominal Strength (Pn)    = {Pn:.2f} kips')
    print(f' LRFD phi*Pn              = {LRFD:.2f} kips')
    print(f' ASD Pn/Omega             = {ASD:.2f} kips')
    print(f'---------------------------------------')
# This line returns all results as a list so they can be used later for plotting.
    return [shape_name, L, Ag, x_bar, U, Ae, Pn, LRFD, ASD]

In [ ]:
#Still need to code the graphs and charts using the results made from this file.